name: bus_cargo_tracker
description: UNEx Logistics — bus cargo tracking application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location & GPS
  geolocator: ^11.0.0

  # Cryptography (OTP hashing)
  crypto: ^3.0.3

  # File & sharing
  image_picker: ^1.0.7
  path_provider: ^2.1.4
  path: ^1.9.0
  share_plus: ^10.0.2

  # Documents & printing
  pdf: ^3.10.8
  esc_pos_utils_plus: ^2.0.4
  flutter_pos_printer_platform_image_3: ^1.2.4

  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.0

  # Networking
  http: ^1.6.0

  # Utilities
  url_launcher: ^6.3.0
  uuid: ^4.5.3
  connectivity_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/UNEX_logistics.png